### ISSUE TITLE
Unordered Current TODO List

### ISSUE THREAD

**Issue by ezalenski** [acm-uic/ACM-API#9]
- [ ] fix account linking
- [ ] authentication
- [ ] proper logging (I wonder if we can incorporate splunk?)
- [ ] redis!!!
    1. - [ ] caching requests to Google Calendar API
    2. - [ ] storing up to date leader board on server startup and update as points change (faster than updating a database table I think? maybe not, talk to chase about this)
    3. - [ ] think of more things to cache....
- [ ] add current position in leaderboard to user information
- [ ] add route to dump leaderboard data
- [ ] replace said route with pagination
- [ ] think of more things to do....

**Comment by clee231** [comment]
Uhh... Splunk isn't free.. is it?
I would suggest the elastic stack, since it is open-source and free. 😃 

You can actually just start using the Caching façade, provided by Laravel.
As far as the application developer is concerned, the implementation shouldn't change whenever we do decide to switch to Redis or some other backing caching driver.  Function calls remain the same, since Laravel provides a nice wrapper for all the drivers it supports.

As far as your second point under the redis checkbox is concerned, redis is probably unlikely to give you any performance benefit at this point. MariaDB as well as many good caching drivers already do a lot of their operations in RAM, so the performance benefit is negligible until you start getting into large datasets.  If you ask me, it'll probably be better to just re-query for the leaderboard data whenever the request is needed.  No need to generate it on server startup and keep it in memory/cache.

For Pagination, this is useful 😄 : https://laravel.com/docs/5.3/pagination

Other things that I can think of at the moment:

- [ ] Provide some way to reset points
- [ ] Provide a secondary method of signing in to an event.
      - Perhaps they lost their I-Card. Maybe make them enter in their UIN and their netid or name?
- [ ] Create a route to return all current transaction data for a given user

**Comment by ezalenski** [comment]
Splunk's free but it limits you on the amount of indexing you can do which I don't think we'll reach until a looooot of logging, but I would like to learn how to use elastic search so I would love to use elastic stack.

Sweet, I'll have to look into the caching façade, I was thinking Redis wouldn't be that bad to just do initially depending on if it's already setup on our servers. Only because I have an idea already how to do the caching with Redis but I'm not sure how it would work with façade, TBD.

Cool, good to know about MariaDB. Regarding the leaderboard do you think it would be better to just calculate all that information (via queries) each request, or keep a leaderboard table? 

Regarding the secondary method for signin, I can just add optional params to the signin route which allows validation of username/netid/name/email so we just need to choose whatever makes sense. Right now the front-end can just leave a box too where you fill in your UIN and make a post request with that to signin (I feel like one issue though is people might find a way to signin without actually being at the event).

Also I've been trying to think about how to update events transactions from any event value changes and I wonder if we should just use the eid to look up all of the point values instead of keeping it in table because if the interval changes it'll be way more difficult than it needs to be to change how the bonus is changed and applied and moved around.

- [ ] Setup some sort of scheduled backup for DB

**Comment by clee231** [comment]
I see... I didn't see the free option.

Regarding the leaderboard, you'll probably just want to calculate all that information and dump it into caching.  If at any point another transaction is created, then invalidate the cache and wait for the next time the data is requested to regenerate and cache the data again.

As for the secondary method for signin, I feel like we need at least two points of information to verify if they were actually there. Netids are pretty commonplace, UINs--not so much.  Perhaps Netid and UIN will be enough to verify?  We'll probably need a longer discussion about it with Mac.

Eid is already in the transactions table, so you should already be able to lookup all point values, right?  I guess we really need to know if we always want to update previous point values when intervals or point values change. Would admins have the option to choose whether or not to update the previous transactions? Or will they just want updated point values for events moving forward... Maybe Mac has more input?

As far as database backups go, all ACM databases are backed-up weekly already.  Do you think we need that to be more frequent?

**Comment by ezalenski** [comment]
Yeah I definitely think we'll need to have a longer discussion about secondary methods, it'll probably be linked to how client authentication and permissions will work as well (only admins can sign people in?)

That's a good point, if we don't want it retroactive then the system is fine as is. If we do want it I believe we'll need to change how the transactions table is organized as while possible it'll be very slow to update previous transactions with how it's organized unless I'm missing an obvious optimization. If we want the ability to choose both then I guess we'd have to do the slow version to allow both to coexist. We should probably have a longer discussion about this as well.

I wasn't aware that we currently backup all databases at all so that's perfect! 😄
